### ISSUE TITLE
Using the underlying profile color...

### ISSUE THREAD

**Issue by JaredEgolf** [AhmedLoud/QcpuUsage#2]
This is great and the first non-IFTTT signal I've tried.  So, is it possible instead of having no light on the higher numbers to allow them to reflect color from the underlying profile?

**Comment by Mubramaj** [comment]
You can get the previous color of a zone using 
https://www.daskeyboard.io/api-resources/signal/get-signal-color-by-zone-id/

**Comment by JaredEgolf** [comment]
Thank you!
